/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programdata;

import java.sql.*; 
import javax.swing.JOptionPane; 
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class FromDelete extends javax.swing.JFrame {
    String user="root"; 
    String pswd ="";
    String host="localhost"; 
    String db="dblogin";
    String url=""; 
    private Connection Lconnection=null; 
    private JTable table=null;

    /**
     * Creates new form FromDelete
     */
    public FromDelete() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver"); 
            url="jdbc:mysql://"+ host +"/"+ db +"?user=" + user + "&password="+ pswd; 
   
            Lconnection=DriverManager.getConnection(url); 
        } 
        catch(ClassNotFoundException e) { System.out.println("Driver tidak ditemukan"); 
        }
        catch (SQLException e){
            System.out.println("koneksi gagal:" + e.toString()); 
        } 
        tampilTabel();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnhapus.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(btnhapus)
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhapus)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        String usrID = 
                table.getValueAt(table.getSelectedRow(),0).toString(); 
        try { 
            PreparedStatement pStatement = null;
         String sql ="DELETE FROM tbldatamhs WHERE nama=? "; 
        pStatement = Lconnection.prepareStatement(sql); 
        pStatement.setString(1, usrID); 
        int intTambah= pStatement.executeUpdate(); 
        if (intTambah>0) JOptionPane.showMessageDialog(this, "Hapus data sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(this, "Hapus data gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
     
        pStatement.close();
        tampilTabel(); 
        }
        catch (SQLException e){ 
            System.out.println("koneksi gagal " + e.toString());
        }
        
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private Object[][] getData(){ 
        Object[][] data1= null;
     try {
         Statement st = Lconnection.createStatement();
     ResultSet rs = st.executeQuery("Select * from tbldatamhs");
     
     rs.last();
     int rowCount= rs.getRow();
     rs.beforeFirst(); 
     data1= new Object[rowCount][5];
     int no=-1;
     while (rs.next()) { 
         no=no+1;
     data1[no][0]=rs.getString("nama"); 
     data1[no][1]=rs.getString("alamat"); 
     data1[no][2]=rs.getString("telepon"); 
     data1[no][3]=rs.getString("handphone"); 
     data1[no][4]=rs.getString("fakultas"); 
     } 
     st.close();
     }
     catch (SQLException e){ 
         System.out.println("koneksi gagal " + e.toString());
     } 
     return data1;
    }
    private void tampilTabel() {
        String[] columnNames = {"nama", "alamat", "telepon", "handphone","fakultas"}; 
        table = new JTable(getData(), columnNames); 
        jScrollPane1.setViewportView(table); 
    
}
}
